DirectoryPath: _site
CheckDoctype: false
EnforceHTML5: true 
EnfroceHTTPS: true 
IgnoreAltMissing: true 
IgnoreURLs:
# CHECK: Feel like we do in fact want to check NT links...?
# - "newtheatre.org.uk"
# - "alpha.newtheatre.org.uk"
# - "history.newtheatre.org.uk"
# - "photos.smugmug.com"
# - "photos.newtheatre.org.uk"
- "twitter.com/thenewtheatre"
- "instagram.com/nottinghamnewtheatre"
- "newtheatre.us3.list-manage.com"
- "stagingchange.com"
