source 'https://rubygems.org'

gem 'rake'
gem 'jekyll', '~> 3.0.0'
gem 'liquid-c'
gem 'jekyll-sitemap'
gem 'jekyll-redirect-from'
gem 'jekyll-coffeescript'
gem 'jekyll-jsminify'
gem 'mini_magick'
gem 'git'
gem 'html-proofer', '~>2.6'
gem 'httparty'
