---
- alias: ef-casting
  name: EdFringe Casting
  date: tbc
- alias: ef-auditions-callbacks
  name: EdFringe Callbacks
  date: tbc
- alias: ef-auditions
  name: 'EdFringe Auditions '
  date: tbc
- alias: 'ef-proposals-deadline '
  name: EdFringe Proposals Deadline
  date: tbc
- alias: ih-proposal-deadline
  name: In House Proposal Deadline
  date: 9th October, 2024
- alias: ih-auditions
  name: In House Auditions
  date: 17th-18th October, 2024
- alias: ih-auditions-callbacks
  name: In House Callbacks
  date: 19th October, 2024
- alias: ih-auditions-casting
  name: In House Casting
  date: 20th October, 2024
- alias: ih-season-launch
  name: In House Season Launch
  date: 16th October, 2024
- alias: fringe-proposal-deadline
  name: Studio Proposal Deadline
  date: 27th October, 2024
- alias: fr-auditions
  name: Studio Auditions
  date: 31st October-1st November, 2024
- alias: fr-auditions-callbacks
  name: Studio Callbacks
  date: 2nd November, 2024
- alias: fr-auditions-casting
  name: Studio Casting
  date: 3rd November, 2024
- alias: fr-season-launch
  name: Studio Season Launch
  date: 30th October, 2024
- alias: ih-slot-1
  name: In House Slot 1
  date: 14th-16th November, 2024
- alias: ih-slot-2
  name: In House Slot 2
  date: 21st-23rd November, 2024
- alias: ih-slot-3
  name: In House Slot 3
  date: 28th-30th November, 2024
- alias: ih-slot-4
  name: In House Slot 4
  date: 5th-7th December, 2024
- alias: ih-slot-5
  name: In House Slot 5
  date: ''
- alias: ih-slot-6
  name: In House Slot 6
  date: ''
- alias: fr-slot-1
  name: Studio Slot 1
  date: 24th-26th November, 2024
- alias: fr-slot-2
  name: Studio Slot 2
  date: 1st-3rd December, 2024
- alias: fr-slot-3
  name: Studio Slot 3
  date: 8th-10th December, 2024
- alias: fr-slot-4
  name: Studio Slot 4
  date: ''
- alias: fr-slot-5
  name: Studio Slot 5
  date: ''
- alias: fr-slot-6
  name: Studio Slot 6
  date: 
- alias: fr-slot-7
  name: Studio Slot 7
  date: ''
- alias: unscripted-1
  name: Creatives
  date: ''
- alias: external-spring
- alias: external-summer
- alias: stuff
  name: StuFF
  date: 13th and 14th June 2025
- alias: audition-deadline
  name: Audition Deadline
  date: ''
- alias: callbacks-2021
  name: Callbacks Announcement for Spring 2021
  date: ''
- alias: callbacks-day-2021
  name: Callbacks for Spring 2021
  date: ''
- alias: casting-2021
  name: Casting for Spring 2021
  date: ''
